/*
 * jedinstl.h - Header file for jEditLauncher installation module
 * Copyright (C) 2001 John Gellene
 * jgellene@nyc.rr.com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * Notwithstanding the terms of the General Public License, the author grants
 * permission to compile and link object code generated by the compilation of
 * this program with object code and libraries that are not subject to the
 * GNU General Public License, provided that the executable output of such
 * compilation shall be distributed with source code on substantially the
 * same basis as the jEditLauncher package of which this program is a part.
 * By way of example, a distribution would satisfy this condition if it
 * included a working makefile for any freely available make utility that
 * runs on the Windows family of operating systems. This condition does not
 * require a licensee of this software to distribute any proprietary software
 * (including header files and libraries) that is licensed under terms
 * prohibiting redistribution to third parties.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * $Id: jedinstl.h,v 1.2 2002/01/22 06:03:21 jgellene Exp $
 */

#define IDS_JEL_VERSION_BASE 1024
#define IDS_JEL_V31 IDS_VERSION_01
#define IDS_JEL_V32 IDS_VERSION_02
#define IDS_JEL_V40 IDS_VERSION_03

#define IDS_JEL_VERSION_NAME_BASE 1056
#define IDS_JEL_VNAME31 IDS_JEL_VERSION_NAME_01
#define IDS_JEL_VNAME32 IDS_JEL_VERSION_NAME_02
#define IDS_JEL_VNAME40 IDS_JEL_VERSION_NAME_03

#define NOT_RUN				0
#define INSTALL_ERROR		-1
#define INSTALL_OK			1
#define INSTALL_REBOOT		2

#include "resource.h"


